from __future__ import annotations

from typing import Any


class MockLLMProvider:
    name = "mock"

    async def enrich(self, markdown: str, *, context: dict[str, Any]) -> str:
        return (
            markdown
            + "\n\n---\n\n"
            + "## Wording Enrichment (Mock)\n\n"
            + "This section was generated by the mock LLM provider for deterministic testing.\n"
        )
